### ISSUE TITLE
crash when \l

### ISSUE THREAD

**Issue by denzow** [denzow/redaql#22]
```
dwh=# \l 3839
select
:
order by 1 desc,2 desc
Traceback (most recent call last):
  File "/home/denzow/.pyenv/versions/aws/bin/redasql", line 10, in <module>
    sys.exit(main())
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 255, in main
    command.loop()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 147, in loop
    self.main()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 167, in main
    self._input_handler(answer)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 179, in _input_handler
    self.execute_meta_command_handler(input_text)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 219, in execute_meta_command_handler
    meta_command_return_list.apply(self)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/dto.py", line 230, in apply
    getattr(new_target, attribute.method_name)(attribute.value)
AttributeError: 'MainCommand' object has no attribute 'append_string'
(aws) denzow@denpad:~$ 

```

**Comment by denzow** [comment]
https://github.com/denzow/redasql/pull/25
