### ISSUE TITLE
\i no such file or directory crash

### ISSUE THREAD

**Issue by denzow** [denzow/redaql#28]
```
prd-read-replica=# \i ?
Traceback (most recent call last):
  File "/home/denzow/.pyenv/versions/aws/bin/redasql", line 10, in <module>
    sys.exit(main())
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 254, in main
    command.loop()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 146, in loop
    self.main()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 166, in main
    self._input_handler(answer)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 178, in _input_handler
    self.execute_meta_command_handler(input_text)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 214, in execute_meta_command_handler
    meta_command_return_list = e.exec(*args)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/metacommand_executor.py", line 292, in exec
    with open(file_name, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '?'

```

**Comment by denzow** [comment]
https://github.com/denzow/redasql/pull/29
