### ISSUE TITLE
crash when load query

### ISSUE THREAD

**Issue by denzow** [denzow/redaql#43]
```
query_results=# \l 1892
Traceback (most recent call last):
  File "/home/denzow/.pyenv/versions/aws/bin/redasql", line 10, in <module>
    sys.exit(main())
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 219, in main
    command.loop()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 105, in loop
    self.main()
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 125, in main
    self._input_handler(answer)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 137, in _input_handler
    self.execute_meta_command_handler(input_text)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/command.py", line 179, in execute_meta_command_handler
    meta_command_return_list = e.exec(*args)
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/metacommand_executor.py", line 227, in exec
    query_response = self.client.get_query_by_id(int(query_id))
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/api_client.py", line 67, in get_query_by_id
    return QueryResponse.from_response(res.json())
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/dto.py", line 197, in from_response
    for p in response['options']['parameters']
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/dto.py", line 197, in <listcomp>
    for p in response['options']['parameters']
  File "/home/denzow/.pyenv/versions/3.7.5/envs/aws/lib/python3.7/site-packages/redasql/dto.py", line 179, in from_response
    parent_query_id=response['parentQueryId']
KeyError: 'parentQueryId'

```

**Comment by denzow** [comment]
related

```
Traceback (most recent call last):
  File "/home/denzow/.pyenv/versions/default/bin/redasql", line 8, in <module>
    sys.exit(main())
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/command.py", line 219, in main
    command.loop()
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/command.py", line 105, in loop
    self.main()
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/command.py", line 125, in main
    self._input_handler(answer)
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/command.py", line 137, in _input_handler
    self.execute_meta_command_handler(input_text)
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/command.py", line 179, in execute_meta_command_handler
    meta_command_return_list = e.exec(*args)
  File "/home/denzow/.pyenv/versions/3.9.16/envs/default/lib/python3.9/site-packages/redasql/metacommand_executor.py", line 248, in exec
    if query_response.data_source_id != self.data_source.id:
AttributeError: 'NoneType' object has no attribute 'id'

```
